# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 412e573781f4c4394aed0f729e8a86ac98ef2fffb39421505be4fb3af7bb5ab8e05a3b467188a38ead7c4ff4a49b709cb7a37b920a033a2c1254df168f694854

test:
  secret_key_base: 06533faa7b0c48ee8cfbcd5f3921dc0c696e80844b87ffe4578490f8bb0ffcc4331af9e30b6c342f2c7cab41ca2aacf356ef0290a9810ea4a6c3e4149a02aa43

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
